In [14]:
import pandas as pd
import requests as r 
response= r.get("https://fake-json-api.mock.beeceptor.com/users")
userresponse=response.json()
# print(userresponse)
df=pd.DataFrame(userresponse)
# print(df)
# df.head()
df.columns
df.isnull().sum()
df.dtypes
df.describe(include="object")

,name,company,username,email,address,zip,state,country,phone,photo
count,10,10,10,10,10,10,10,10,10,10
unique,10,10,10,10,10,10,9,10,10,10
top,Judson Padberg,"Nolan, Herzog and Okuneva",Earlene_Moen,Diego55@gmail.com,11015 Cornelius Trail,74924,Michigan,Antarctica,(479) 593-7042 x5354,https://json-server.dev/ai-profiles/28.png
freq,1,1,1,1,1,1,2,1,1,1

In [29]:
headers={
    'Content-Type':'application/json',
}
credentials={'email':'john@mail.com','password':'changeme'}
userprofileurl='https://api.escuelajs.co/api/v1/auth/login'
response=r.post(userprofileurl,credentials,headers)
print(response.json())

access_token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTc3NTQ4NzYzOCwiZXhwIjoxNzc3MjE1NjM4fQ.Xg6noodFfCfTuKIe-yiEvHMZbkDSxWAt82jP04lSy2E'

SyntaxError: invalid syntax (772567517.py, line 7)

In [32]:
headers={
     'Authorization':'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTc3NTQ4NzYzOCwiZXhwIjoxNzc3MjE1NjM4fQ.Xg6noodFfCfTuKIe-yiEvHMZbkDSxWAt82jP04lSy2E'
}
credentials={'email':'john@mail.com','password':'changeme'}
userprofileurl='https://api.escuelajs.co/api/v1/auth/profile'
response=r.get(userprofileurl,headers=headers)
data=response.json()

In [33]:
df = pd.DataFrame([data])

In [37]:
df.to_csv("userInfo")
print("userInfo saved successfully")

userInfo saved successfully

In [38]:
df.head()

,id,email,password,name,role,avatar,creationAt,updatedAt
0,1,john@mail.com,changeme,Jhon,customer,https://i.imgur.com/LDOO4Qs.jpg,2026-04-06T03:15:21.000Z,2026-04-06T03:15:21.000Z

In [44]:
import requests

url = "https://i.imgur.com/LDOO4Qs.jpeg"

response = requests.get(url)



with open("avatar.jpeg", "wb") as file:
        file.write(response.content)
        print("Image downloaded successfully")

Image downloaded successfully

In [43]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (4.35.0)
Requirement already satisfied: urllib3<3.0,>=2.5.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (2.5.0)
Requirement already satisfied: trio~=0.30.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from selenium) (0.30.0)
Requirement already satisfied: trio-websocket~=0.12.2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: certifi>=2025.6.15 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from selenium) (2025.7.14)
Requirement already satisfied: typing_extensions~=4.14.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from selenium) (4.14.1)
Requirement already satisfied: websocket-client~=1.8.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from trio~=0.30.0->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from trio~=0.30.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from trio~=0.30.0->selenium) (3.10)
Requirement already satisfied: outcome in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from trio~=0.30.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from trio~=0.30.0->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from trio~=0.30.0->selenium) (2.0.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from trio-websocket~=0.12.2->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from cffi>=1.14->trio~=0.30.0->selenium) (2.22)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.12.2->selenium) (0.16.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip