In [14]:
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn

In [15]:
data=pd.read_csv(r"C:\Users\User\Downloads\Compressed\archive_15\HR_Analytics.csv")
pd.set_option('display.max_columns', None)

In [17]:
data.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,SalarySlab,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,1,405,3,Male,54,3,1,Laboratory Technician,3,Single,1420,Upto 5k,25233,1,Y,No,13,3,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,1,411,4,Female,69,2,1,Sales Representative,3,Single,1200,Upto 5k,9724,1,Y,No,12,3,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,1,614,2,Male,69,3,1,Sales Representative,2,Single,1878,Upto 5k,8059,1,Y,Yes,14,3,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,1,1012,2,Male,73,3,1,Research Scientist,4,Single,1051,Upto 5k,13493,1,Y,No,15,3,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,1,1156,3,Male,80,3,1,Laboratory Technician,3,Single,1904,Upto 5k,13556,1,Y,No,12,3,4,80,0,0,0,3,0,0,0,0.0

In [6]:
data.columns

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'SalarySlab',
       'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1480 entries, 0 to 1479
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1480 non-null   object
 1   Age                       1480 non-null   int64
 2   AgeGroup                  1480 non-null   object
 3   Attrition                 1480 non-null   object
 4   BusinessTravel            1480 non-null   object
 5   DailyRate                 1480 non-null   int64
 6   Department                1480 non-null   object
 7   DistanceFromHome          1480 non-null   int64
 8   Education                 1480 non-null   int64
 9   EducationField            1480 non-null   object
 10  EmployeeCount             1480 non-null   int64
 11  EmployeeNumber            1480 non-null   int64
 12  EnvironmentSatisfaction   1480 non-null   int64
 13  Gender                    1480 non-null   object
 14  HourlyRate                1480 non-null   int64
 15  JobInvolvement            1480 non-null   int64
 16  JobLevel                  1480 non-null   int64
 17  JobRole                   1480 non-null   object
 18  JobSatisfaction           1480 non-null   int64
 19  MaritalStatus             1480 non-null   object
 20  MonthlyIncome             1480 non-null   int64
 21  SalarySlab                1480 non-null   object
 22  MonthlyRate               1480 non-null   int64
 23  NumCompaniesWorked        1480 non-null   int64
 24  Over18                    1480 non-null   object
 25  OverTime                  1480 non-null   object
 26  PercentSalaryHike         1480 non-null   int64
 27  PerformanceRating         1480 non-null   int64
 28  RelationshipSatisfaction  1480 non-null   int64
 29  StandardHours             1480 non-null   int64
 30  StockOptionLevel          1480 non-null   int64
 31  TotalWorkingYears         1480 non-null   int64
 32  TrainingTimesLastYear     1480 non-null   int64
 33  WorkLifeBalance           1480 non-null   int64
 34  YearsAtCompany            1480 non-null   int64
 35  YearsInCurrentRole        1480 non-null   int64
 36  YearsSinceLastPromotion   1480 non-null   int64
 37  YearsWithCurrManager      1423 non-null   float64
dtypes: float64(1), int64(25), object(12)
memory usage: 439.5+ KB

In [20]:
data.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1480.000000,1480.000000,1480.000000,1480.000000,1480.0,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.0,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1423.000000
mean,36.917568,801.384459,9.220270,2.910811,1.0,1031.860811,2.724324,65.845270,2.729730,2.064865,2.725000,6504.985811,14298.460811,2.687162,15.210135,3.153378,2.708784,80.0,0.791892,11.281757,2.797973,2.760811,7.009459,4.228378,2.182432,4.118060
std,9.128559,403.126988,8.131201,1.023796,0.0,605.955046,1.092579,20.328266,0.713007,1.105574,1.104137,4700.261400,7112.056802,2.494098,3.655338,0.360474,1.081995,0.0,0.850527,7.770870,1.288791,0.707024,6.117945,3.616020,3.219357,3.555484
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1009.000000,2094.000000,0.000000,11.000000,3.000000,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,493.750000,2.000000,48.000000,2.000000,1.000000,2.000000,2922.250000,8051.000000,1.000000,12.000000,3.000000,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,800.000000,7.000000,3.000000,1.0,1027.500000,3.000000,66.000000,3.000000,2.000000,3.000000,4933.000000,14220.000000,2.000000,14.000000,3.000000,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1568.250000,4.000000,83.000000,3.000000,3.000000,4.000000,8383.750000,20460.500000,4.000000,18.000000,3.000000,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,4.000000,19999.000000,26999.000000,9.000000,25.000000,4.000000,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [21]:
data.describe(include="object")

,EmpID,AgeGroup,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,SalarySlab,Over18,OverTime
count,1480,1480,1480,1480,1480,1480,1480,1480,1480,1480,1480,1480
unique,1470,5,2,4,3,6,2,9,3,4,1,2
top,RM1468,26-35,No,Travel_Rarely,Research & Development,Life Sciences,Male,Sales Executive,Married,Upto 5k,Y,No
freq,2,611,1242,1042,967,607,889,329,679,753,1480,1062

In [22]:
data.isna().sum()

EmpID                        0
Age                          0
AgeGroup                     0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
DistanceFromHome             0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
HourlyRate                   0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
SalarySlab                   0
MonthlyRate                  0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
PercentSalaryHike            0
PerformanceRating            0
RelationshipSatisfaction     0
StandardHours                0
StockOptionLevel             0
TotalWorkingYears            0
TrainingTimesLastYear        0
WorkLifeBalance              0
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager        57
dtype: int64

In [25]:
data['YearsWithCurrManager'].fillna(data['YearsWithCurrManager'].median,inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_13876\3648145583.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method Series.median of 0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
1475    10.0
1476    11.0
1477     2.0
1478     9.0
1479     0.0
Name: YearsWithCurrManager, Length: 1480, dtype: float64>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data['YearsWithCurrManager'].fillna(data['YearsWithCurrManager'].median,inplace=True)

In [26]:
data['YearsWithCurrManager'].isna().sum()

np.int64(0)

In [27]:
data.isna().sum()

EmpID                       0
Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [28]:
data.columns

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'SalarySlab',
       'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [35]:
q1=data['Age'].quantile(0.25)
print(q1)

30.0

In [36]:
q3=data['Age'].quantile(0.75)
print(q3)

43.0

In [33]:
IQR=q3-q1

In [34]:
print(IQR)

13.0

In [39]:
lower = q1 - 1.5 * IQR
upper = q3 + 1.5 * IQR

In [40]:
data['Age']=data['Age'].clip(lower,upper)

In [42]:
data['Age']


Q1=data['Age'].quantile(0.25)
Q3=data['Age'].quantile(0.75)

In [43]:
IQR1=Q3-Q1

In [44]:
print(IQR1)

13.0

In [48]:
corr_matrix = data.corr(numeric_only=True)

In [49]:
print(corr_matrix)

                               Age  DailyRate  DistanceFromHome  Education  \
Age                       1.000000   0.011584         -0.000329   0.205689
DailyRate                 0.011584   1.000000         -0.007134  -0.016750
DistanceFromHome         -0.000329  -0.007134          1.000000   0.019661
Education                 0.205689  -0.016750          0.019661   1.000000
EmployeeCount                  NaN        NaN               NaN        NaN
EmployeeNumber           -0.011181  -0.054996          0.038137   0.038020
EnvironmentSatisfaction   0.011617   0.019176         -0.013633  -0.026831
HourlyRate                0.022704   0.021349          0.027899   0.019446
JobInvolvement            0.026804   0.043964          0.006427   0.042908
JobLevel                  0.509758   0.001940          0.007360   0.097107
JobSatisfaction          -0.005269   0.034562         -0.004244  -0.012740
MonthlyIncome             0.497486   0.005963         -0.015817   0.092182
MonthlyRate               0.029529  -0.028730          0.025782  -0.026779
NumCompaniesWorked        0.300739   0.038991         -0.028873   0.125433
PercentSalaryHike         0.000864   0.021772          0.036682  -0.009984
PerformanceRating         0.000146  -0.001379          0.024221  -0.023366
RelationshipSatisfaction  0.053632   0.012214          0.002762  -0.005762
StandardHours                  NaN        NaN               NaN        NaN
StockOptionLevel          0.038545   0.042097          0.045153   0.016717
TotalWorkingYears         0.680837   0.015036          0.007802   0.145258
TrainingTimesLastYear    -0.016819   0.004297         -0.035882  -0.026476
WorkLifeBalance          -0.021704  -0.037683         -0.030581   0.008806
YearsAtCompany            0.310550  -0.033737          0.010111   0.065983
YearsInCurrentRole        0.213330   0.010452          0.018593   0.057557
YearsSinceLastPromotion   0.216755  -0.032439          0.011817   0.051507

                          EmployeeCount  EmployeeNumber  \
Age                                 NaN       -0.011181
DailyRate                           NaN       -0.054996
DistanceFromHome                    NaN        0.038137
Education                           NaN        0.038020
EmployeeCount                       NaN             NaN
EmployeeNumber                      NaN        1.000000
EnvironmentSatisfaction             NaN        0.021359
HourlyRate                          NaN        0.030896
JobInvolvement                      NaN       -0.007231
JobLevel                            NaN       -0.016891
JobSatisfaction                     NaN       -0.051062
MonthlyIncome                       NaN       -0.013928
MonthlyRate                         NaN        0.008998
NumCompaniesWorked                  NaN       -0.005340
PercentSalaryHike                   NaN       -0.012501
PerformanceRating                   NaN       -0.021808
RelationshipSatisfaction            NaN       -0.074316
StandardHours                       NaN             NaN
StockOptionLevel                    NaN        0.057548
TotalWorkingYears                   NaN       -0.013731
TrainingTimesLastYear               NaN        0.021525
WorkLifeBalance                     NaN        0.009202
YearsAtCompany                      NaN       -0.010756
YearsInCurrentRole                  NaN       -0.008735
YearsSinceLastPromotion             NaN       -0.011731

                          EnvironmentSatisfaction  HourlyRate  JobInvolvement  \
Age                                      0.011617    0.022704        0.026804
DailyRate                                0.019176    0.021349        0.043964
DistanceFromHome                        -0.013633    0.027899        0.006427
Education                               -0.026831    0.019446        0.042908
EmployeeCount                                 NaN         NaN             NaN
EmployeeNumber                           0.021359    0.030896       -0.007231
EnvironmentSatisfaction                  1.000000   -0.053826       -0.013254
HourlyRate                              -0.053826    1.000000        0.046327
JobInvolvement                          -0.013254    0.046327        1.000000
JobLevel                                 0.000260   -0.028585       -0.013770
JobSatisfaction                         -0.010201   -0.070670       -0.018036
MonthlyIncome                           -0.006913   -0.015981       -0.017496
MonthlyRate                              0.040251   -0.018883       -0.019553
NumCompaniesWorked                       0.013240    0.021169        0.015537
PercentSalaryHike                       -0.032042   -0.008834       -0.014514
PerformanceRating                       -0.031625    0.000750       -0.025382
RelationshipSatisfaction                 0.009256    0.000071        0.032878
StandardHours                                 NaN         NaN             NaN
StockOptionLevel                         0.002250    0.049756        0.022028
TotalWorkingYears                       -0.002472   -0.004128       -0.007114
TrainingTimesLastYear                   -0.016531   -0.010846       -0.018256
WorkLifeBalance                          0.024867   -0.004835       -0.008954
YearsAtCompany                          -0.000318   -0.018848       -0.022974
YearsInCurrentRole                       0.017658   -0.023756        0.005862
YearsSinceLastPromotion                  0.013731   -0.026131       -0.025929

                          JobLevel  JobSatisfaction  MonthlyIncome  \
Age                       0.509758        -0.005269       0.497486
DailyRate                 0.001940         0.034562       0.005963
DistanceFromHome          0.007360        -0.004244      -0.015817
Education                 0.097107        -0.012740       0.092182
EmployeeCount                  NaN              NaN            NaN
EmployeeNumber           -0.016891        -0.051062      -0.013928
EnvironmentSatisfaction   0.000260        -0.010201      -0.006913
HourlyRate               -0.028585        -0.070670      -0.015981
JobInvolvement           -0.013770        -0.018036      -0.017496
JobLevel                  1.000000        -0.001440       0.949835
JobSatisfaction          -0.001440         1.000000      -0.008832
MonthlyIncome             0.949835        -0.008832       1.000000
MonthlyRate               0.039256         0.001553       0.034263
NumCompaniesWorked        0.142472        -0.054832       0.148863
PercentSalaryHike        -0.036669         0.018851      -0.028260
PerformanceRating        -0.021588         0.002421      -0.017379
RelationshipSatisfaction  0.018063        -0.009918       0.022757
StandardHours                  NaN              NaN            NaN
StockOptionLevel          0.015803         0.012456       0.006517
TotalWorkingYears         0.781880        -0.018623       0.771807
TrainingTimesLastYear    -0.017370        -0.006759      -0.021270
WorkLifeBalance           0.038027        -0.017625       0.030430
YearsAtCompany            0.535210        -0.001917       0.514469
YearsInCurrentRole        0.390189        -0.001871       0.364422
YearsSinceLastPromotion   0.355518        -0.014979       0.346065

                          MonthlyRate  NumCompaniesWorked  PercentSalaryHike  \
Age                          0.029529            0.300739           0.000864
DailyRate                   -0.028730            0.038991           0.021772
DistanceFromHome             0.025782           -0.028873           0.036682
Education                   -0.026779            0.125433          -0.009984
EmployeeCount                     NaN                 NaN                NaN
EmployeeNumber               0.008998           -0.005340          -0.012501
EnvironmentSatisfaction      0.040251            0.013240          -0.032042
HourlyRate                  -0.018883            0.021169          -0.008834
JobInvolvement              -0.019553            0.015537          -0.014514
JobLevel                     0.039256            0.142472          -0.036669
JobSatisfaction              0.001553           -0.054832           0.018851
MonthlyIncome                0.034263            0.148863          -0.028260
MonthlyRate                  1.000000            0.019828          -0.007168
NumCompaniesWorked           0.019828            1.000000          -0.010955
PercentSalaryHike           -0.007168           -0.010955           1.000000
PerformanceRating           -0.011296           -0.014278           0.772420
RelationshipSatisfaction    -0.001620            0.053158          -0.038197
StandardHours                     NaN                 NaN                NaN
StockOptionLevel            -0.033070            0.032079           0.007334
TotalWorkingYears            0.026417            0.237728          -0.022414
TrainingTimesLastYear        0.004872           -0.062797          -0.007631
WorkLifeBalance              0.009111           -0.006804          -0.001991
YearsAtCompany              -0.024907           -0.119490          -0.037217
YearsInCurrentRole          -0.012644           -0.090808          -0.003326
YearsSinceLastPromotion      0.001412           -0.037012          -0.024576

                          PerformanceRating  RelationshipSatisfaction  \
Age                                0.000146                  0.053632
DailyRate                         -0.001379                  0.012214
DistanceFromHome                   0.024221                  0.002762
Education                         -0.023366                 -0.005762
EmployeeCount                           NaN                       NaN
EmployeeNumber                    -0.021808                 -0.074316
EnvironmentSatisfaction           -0.031625                  0.009256
HourlyRate                         0.000750                  0.000071
JobInvolvement                    -0.025382                  0.032878
JobLevel                          -0.021588                  0.018063
JobSatisfaction                    0.002421                 -0.009918
MonthlyIncome                     -0.017379                  0.022757
MonthlyRate                       -0.011296                 -0.001620
NumCompaniesWorked                -0.014278                  0.053158
PercentSalaryHike                  0.772420                 -0.038197
PerformanceRating                  1.000000                 -0.031020
RelationshipSatisfaction          -0.031020                  1.000000
StandardHours                           NaN                       NaN
StockOptionLevel                   0.004941                 -0.046063
TotalWorkingYears                  0.005320                  0.023918
TrainingTimesLastYear             -0.019123                  0.001904
WorkLifeBalance                    0.003438                  0.018481
YearsAtCompany                     0.003021                  0.017678
YearsInCurrentRole                 0.033798                 -0.016516
YearsSinceLastPromotion            0.017239                  0.031373

                          StandardHours  StockOptionLevel  TotalWorkingYears  \
Age                                 NaN          0.038545           0.680837
DailyRate                           NaN          0.042097           0.015036
DistanceFromHome                    NaN          0.045153           0.007802
Education                           NaN          0.016717           0.145258
EmployeeCount                       NaN               NaN                NaN
EmployeeNumber                      NaN          0.057548          -0.013731
EnvironmentSatisfaction             NaN          0.002250          -0.002472
HourlyRate                          NaN          0.049756          -0.004128
JobInvolvement                      NaN          0.022028          -0.007114
JobLevel                            NaN          0.015803           0.781880
JobSatisfaction                     NaN          0.012456          -0.018623
MonthlyIncome                       NaN          0.006517           0.771807
MonthlyRate                         NaN         -0.033070           0.026417
NumCompaniesWorked                  NaN          0.032079           0.237728
PercentSalaryHike                   NaN          0.007334          -0.022414
PerformanceRating                   NaN          0.004941           0.005320
RelationshipSatisfaction            NaN         -0.046063           0.023918
StandardHours                       NaN               NaN                NaN
StockOptionLevel                    NaN          1.000000           0.011537
TotalWorkingYears                   NaN          0.011537           1.000000
TrainingTimesLastYear               NaN          0.011581          -0.034820
WorkLifeBalance                     NaN          0.004868           0.000091
YearsAtCompany                      NaN          0.015581           0.627569
YearsInCurrentRole                  NaN          0.051078           0.459987
YearsSinceLastPromotion             NaN          0.016097           0.405426

                          TrainingTimesLastYear  WorkLifeBalance  \
Age                                   -0.016819        -0.021704
DailyRate                              0.004297        -0.037683
DistanceFromHome                      -0.035882        -0.030581
Education                             -0.026476         0.008806
EmployeeCount                               NaN              NaN
EmployeeNumber                         0.021525         0.009202
EnvironmentSatisfaction               -0.016531         0.024867
HourlyRate                            -0.010846        -0.004835
JobInvolvement                        -0.018256        -0.008954
JobLevel                              -0.017370         0.038027
JobSatisfaction                       -0.006759        -0.017625
MonthlyIncome                         -0.021270         0.030430
MonthlyRate                            0.004872         0.009111
NumCompaniesWorked                    -0.062797        -0.006804
PercentSalaryHike                     -0.007631        -0.001991
PerformanceRating                     -0.019123         0.003438
RelationshipSatisfaction               0.001904         0.018481
StandardHours                               NaN              NaN
StockOptionLevel                       0.011581         0.004868
TotalWorkingYears                     -0.034820         0.000091
TrainingTimesLastYear                  1.000000         0.027813
WorkLifeBalance                        0.027813         1.000000
YearsAtCompany                         0.002815         0.009902
YearsInCurrentRole                    -0.004311         0.047563
YearsSinceLastPromotion               -0.002192         0.007896

                          YearsAtCompany  YearsInCurrentRole  \
Age                             0.310550            0.213330
DailyRate                      -0.033737            0.010452
DistanceFromHome                0.010111            0.018593
Education                       0.065983            0.057557
EmployeeCount                        NaN                 NaN
EmployeeNumber                 -0.010756           -0.008735
EnvironmentSatisfaction        -0.000318            0.017658
HourlyRate                     -0.018848           -0.023756
JobInvolvement                 -0.022974            0.005862
JobLevel                        0.535210            0.390189
JobSatisfaction                -0.001917           -0.001871
MonthlyIncome                   0.514469            0.364422
MonthlyRate                    -0.024907           -0.012644
NumCompaniesWorked             -0.119490           -0.090808
PercentSalaryHike              -0.037217           -0.003326
PerformanceRating               0.003021            0.033798
RelationshipSatisfaction        0.017678           -0.016516
StandardHours                        NaN                 NaN
StockOptionLevel                0.015581            0.051078
TotalWorkingYears               0.627569            0.459987
TrainingTimesLastYear           0.002815           -0.004311
WorkLifeBalance                 0.009902            0.047563
YearsAtCompany                  1.000000            0.758964
YearsInCurrentRole              0.758964            1.000000
YearsSinceLastPromotion         0.619236            0.548418

                          YearsSinceLastPromotion
Age                                      0.216755
DailyRate                               -0.032439
DistanceFromHome                         0.011817
Education                                0.051507
EmployeeCount                                 NaN
EmployeeNumber                          -0.011731
EnvironmentSatisfaction                  0.013731
HourlyRate                              -0.026131
JobInvolvement                          -0.025929
JobLevel                                 0.355518
JobSatisfaction                         -0.014979
MonthlyIncome                            0.346065
MonthlyRate                              0.001412
NumCompaniesWorked                      -0.037012
PercentSalaryHike                       -0.024576
PerformanceRating                        0.017239
RelationshipSatisfaction                 0.031373
StandardHours                                 NaN
StockOptionLevel                         0.016097
TotalWorkingYears                        0.405426
TrainingTimesLastYear                   -0.002192
WorkLifeBalance                          0.007896
YearsAtCompany                           0.619236
YearsInCurrentRole                       0.548418
YearsSinceLastPromotion                  1.000000

In [53]:
data.drop(['EmpID'], axis=1, inplace=True)

In [55]:
data.columns

data = pd.get_dummies(data, drop_first=True)

In [60]:
data.columns

Index(['Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel',
       'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion', 'AgeGroup_26-35',
       'AgeGroup_36-45', 'AgeGroup_46-55', 'AgeGroup_55+', 'Attrition_Yes',
       'BusinessTravel_TravelRarely', 'BusinessTravel_Travel_Frequently',
       'BusinessTravel_Travel_Rarely', 'Department_Research & Development',
       'Department_Sales', 'EducationField_Life Sciences',
       'EducationField_Marketing', 'EducationField_Medical',
       'EducationField_Other', 'EducationField_Technical Degree',
       'Gender_Male', 'JobRole_Human Resources',
       'JobRole_Laboratory Technician', 'JobRole_Manager',
       'JobRole_Manufacturing Director', 'JobRole_Research Director',
       'JobRole_Research Scientist', 'JobRole_Sales Executive',
       'JobRole_Sales Representative', 'MaritalStatus_Married',
       'MaritalStatus_Single', 'SalarySlab_15k+', 'SalarySlab_5k-10k',
       'SalarySlab_Upto 5k', 'OverTime_Yes', 'YearsWithCurrManager_1.0',
       'YearsWithCurrManager_2.0',
       'YearsWithCurrManager_<bound method Series.median of 0        0.0\n1        0.0\n2        0.0\n3        0.0\n4        0.0\n        ... \n1475    10.0\n1476    11.0\n1477     2.0\n1478     9.0\n1479     0.0\nName: YearsWithCurrManager, Length: 1480, dtype: object>',
       'YearsWithCurrManager_3.0', 'YearsWithCurrManager_4.0',
       'YearsWithCurrManager_5.0', 'YearsWithCurrManager_6.0',
       'YearsWithCurrManager_7.0', 'YearsWithCurrManager_8.0',
       'YearsWithCurrManager_9.0', 'YearsWithCurrManager_10.0',
       'YearsWithCurrManager_12.0', 'YearsWithCurrManager_13.0',
       'YearsWithCurrManager_11.0', 'YearsWithCurrManager_15.0',
       'YearsWithCurrManager_14.0', 'YearsWithCurrManager_17.0',
       'YearsWithCurrManager_16.0'],
      dtype='object')

In [57]:
X = data.drop('', axis=1)

KeyError: "['Attrition'] not found in axis"

In [61]:
data.columns

Index(['Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel',
       'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion', 'AgeGroup_26-35',
       'AgeGroup_36-45', 'AgeGroup_46-55', 'AgeGroup_55+', 'Attrition_Yes',
       'BusinessTravel_TravelRarely', 'BusinessTravel_Travel_Frequently',
       'BusinessTravel_Travel_Rarely', 'Department_Research & Development',
       'Department_Sales', 'EducationField_Life Sciences',
       'EducationField_Marketing', 'EducationField_Medical',
       'EducationField_Other', 'EducationField_Technical Degree',
       'Gender_Male', 'JobRole_Human Resources',
       'JobRole_Laboratory Technician', 'JobRole_Manager',
       'JobRole_Manufacturing Director', 'JobRole_Research Director',
       'JobRole_Research Scientist', 'JobRole_Sales Executive',
       'JobRole_Sales Representative', 'MaritalStatus_Married',
       'MaritalStatus_Single', 'SalarySlab_15k+', 'SalarySlab_5k-10k',
       'SalarySlab_Upto 5k', 'OverTime_Yes', 'YearsWithCurrManager_1.0',
       'YearsWithCurrManager_2.0',
       'YearsWithCurrManager_<bound method Series.median of 0        0.0\n1        0.0\n2        0.0\n3        0.0\n4        0.0\n        ... \n1475    10.0\n1476    11.0\n1477     2.0\n1478     9.0\n1479     0.0\nName: YearsWithCurrManager, Length: 1480, dtype: object>',
       'YearsWithCurrManager_3.0', 'YearsWithCurrManager_4.0',
       'YearsWithCurrManager_5.0', 'YearsWithCurrManager_6.0',
       'YearsWithCurrManager_7.0', 'YearsWithCurrManager_8.0',
       'YearsWithCurrManager_9.0', 'YearsWithCurrManager_10.0',
       'YearsWithCurrManager_12.0', 'YearsWithCurrManager_13.0',
       'YearsWithCurrManager_11.0', 'YearsWithCurrManager_15.0',
       'YearsWithCurrManager_14.0', 'YearsWithCurrManager_17.0',
       'YearsWithCurrManager_16.0'],
      dtype='object')